<div class="site-label-2">
    The Beverly Hills SLS is our recommended hotel for the event, located one block from the Beverly Center and just a few blocks from the sparkling storefronts of Rodeo Drive and The Grove.  Each of the Philippe Stark-designed guest rooms and suites are ultra-modern and classically elegant – just what you would expect from Beverly Hills.
</div>

<p>    
    <div class="site-label-2">
        SLS Beverly Hills<br>
        465 S. La Cienega Blvd.<br>
        Los Angeles, CA 90048<br>
    </div>
</p>

<div class="site-label-2">
    To book your sleeping room, please contact the hotel at (888) 627-8543 and refer to “Rolls-Royce”.  Please note that we are only holding a small block of bedrooms at the pre-negotiated event rate.  RRMC NA will not be booking hotel rooms on your behalf.  Please remember to contact the hotel directly to reserve your sleeping room.  All attendees are responsible for settling their own room bill and incidentals upon check-out.  All rooms are subject to availability at the SLS Beverly Hills at the time of booking.
</div>