<div class="site-label-2">
    Our recommended hotel for the event, the Viceroy Miami, is the centerpiece of the groundbreaking Icon Brickell project, a ten-acre bay-front enclave adjacent to historical Miami River Circle Park.  The hotel is within walking distance of the Brickell financial district and minutes from American Airlines Arena and the Adrienne Ascht Center for the Performing Arts.
</div>

<p>
    <div class="site-label-2">
        Viceroy Miami<br>
        485 Brickell Avenue<br>
        Miami, FL 33131<br>
    </div>    
</p>

<div class="site-label-2">
    To book your sleeping room, please contact the hotel at (305) 503-4400 and request the “Rolls-Royce Group Rate”.  Please note that we are only holding a small block of bedrooms at the pre-negotiated event rate.  RRMC NA will not be booking hotel rooms on your behalf.  Please remember to contact the hotel directly to reserve your sleeping room.  All attendees are responsible for settling their own room bill and incidentals upon check-out.  All rooms are subject to availability at the Viceroy Miami at the time of booking.
</div>